/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EndParse.java
 *
 * Created on 17-ott-2011, 16.25.21
 */
package panel;

import javax.swing.JLabel;

/**
 *
 * @author claudiofior
 */
public class EndParse extends javax.swing.JPanel {
	private controler.Controler controler;
	public JLabel getJLabelFile () {
		return this.jLabelFile;
	}
	public JLabel getJLabelCount () {
		return this.jLabelCount;
	}
	public JLabel getJLabelTime () {
		return this.jLabelTime;
	}
	public EndParse(controler.Controler controler) {
		this();
		this.controler = controler;
	}
	/** Creates new form EndParse */
	public EndParse() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jLabelFileL = new javax.swing.JLabel();
        jLabelCountL = new javax.swing.JLabel();
        jLabelTimeL = new javax.swing.JLabel();
        jLabelFile = new javax.swing.JLabel();
        jLabelCount = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jButtonChooseFile = new javax.swing.JButton();

        jLabel.setText("L'elaborazione del file è conclusa");

        jLabelFileL.setText("File generato:");

        jLabelCountL.setText("Numero di voci:");

        jLabelTimeL.setText("Tempo richiesto:");

        jButtonChooseFile.setText("Seleziona un'altro file");
        jButtonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCountL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(jLabelCount))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFileL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(jLabelFile))
                    .addComponent(jLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTimeL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jLabelTime)
                        .addGap(135, 135, 135)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jButtonChooseFile)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFileL)
                    .addComponent(jLabelFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountL)
                    .addComponent(jLabelCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTimeL)
                    .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jButtonChooseFile)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFileActionPerformed
		controler.UpdateUI updateUI = new controler.UpdateUI() {
		public void run() { 
			controler.Action <String,Object>  action = new controler.Action <String,Object> (); 
			action.put("task", "openfile"); 		
			this.controler.task_checkout(action); 			} 
		};
		updateUI.set_task(this.controler);
		javax.swing.SwingUtilities.invokeLater(updateUI);
	}//GEN-LAST:event_jButtonChooseFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChooseFile;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelCount;
    private javax.swing.JLabel jLabelCountL;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelFileL;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTimeL;
    // End of variables declaration//GEN-END:variables
}
