/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenFile.java
 *
 * Created on 17-ott-2011, 10.34.33
 */
package panel;

import java.io.File;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author claudiofior
 */
public class OpenFile extends javax.swing.JPanel {
	class CsvFileFilter extends FileFilter{
		private final String[] okFileExtensions = new String[] {"csv"};
		
		public boolean accept(File f){
			for (String extension : okFileExtensions)
			{
			  if (f.getName().toLowerCase().endsWith(extension))
			  {
				return true;
			  }
			}
			return false;
		}
		public String getDescription(){
			return "CSV Files";
		}
	}
	private controler.Controler controler;
	/** Creates new form MainFrame */
	public OpenFile(controler.Controler controler) {
		this();
		this.controler = controler;
		this.jFileChooser.setFileFilter(new CsvFileFilter());
	}
	/** Creates new form OpenFile */
	public OpenFile() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelChooser = new javax.swing.JLabel();
        jFileChooser = new javax.swing.JFileChooser();

        jLabelChooser.setText("Seleziona il file da aprire");

        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelChooser))
                    .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelChooser)
                .addGap(18, 18, 18)
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
	    controler.UpdateUI updateUI = null;
		if (evt.getActionCommand() == this.jFileChooser.APPROVE_SELECTION) {
		 updateUI = new controler.UpdateUI() {
				public void run() {
				controler.Action <String,Object>  action = new controler.Action <String,Object> ();
				action.put("task", "parsefile");
				action.put("file", jFileChooser.getSelectedFile());
				this.controler.task_checkout(action);
				}
			};
	   }
		else if (evt.getActionCommand() == this.jFileChooser.CANCEL_SELECTION) {
			updateUI = new controler.UpdateUI() {
				public void run() {
				controler.Action action = new controler.Action();
				this.controler.task_checkout(action);
				}
			};
		}
		updateUI.set_task(this.controler);
		javax.swing.SwingUtilities.invokeLater(updateUI);
	}//GEN-LAST:event_jFileChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabelChooser;
    // End of variables declaration//GEN-END:variables
}
