/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParseFile.java
 *
 * Created on 17-ott-2011, 11.33.45
 */
package panel;

import javax.swing.JLabel;
import javax.swing.JTable;
import controler.UpdateUI;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiofior
 */
public class ParseFile extends javax.swing.JPanel {
	private controler.Controler controler;
	/** Creates new form MainFrame */
	public ParseFile(controler.Controler controler) {
		this();
		this.controler = controler;
	}
	public JTable getTableLog() {
		return this.jTableLog;
	}
	public JLabel getLabelProgress () {
		return this.jLabelProgress;
	}
	/** Creates new form ParseFile */
	public ParseFile() {
		initComponents();
	}
	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProgress = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableLog = new javax.swing.JTable();
        jButtonCancel = new javax.swing.JButton();

        jLabelProgress.setText("Elaborazione in corso");

        jTableLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Apertura file"}
            },
            new String [] {
                "Messaggi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableLog);

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProgress)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		int status = JOptionPane.showConfirmDialog(
			this,
			"Vuoi cancellare la ricerca dei nomi.",
			"Anullare",
			JOptionPane.YES_NO_OPTION
			);
		if (status == JOptionPane.OK_OPTION) {
			controler.UpdateUI updateUI = new controler.UpdateUI() {
			public void run() {
					controler.Action action = new controler.Action();
					this.controler.task_checkout(action);
					}
			};
			updateUI.set_task(this.controler);
			javax.swing.SwingUtilities.invokeLater(updateUI);
		}
		
	}//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableLog;
    // End of variables declaration//GEN-END:variables
}
